### ISSUE TITLE
Is there an Open Source, Creative Commons tied to this great project?

### ISSUE THREAD

**Issue by diondresschers** [acircleda/RESMHandbook#1]
I heard from a university student that this book really helped her to getting on the same level as her team members that have a bit more affinity with R.
 
I was interested, but noticed that there was no copyright/license info for this book as we are investigating if we could use this to help other students and people interested in R.

So my questions, is there an Open Access [1], or Creative Commons [1] tied to this great project?

# References:

* [1] [Berlin Declaration | Max Planck Open Access](https://openaccess.mpg.de/Berlin-Declaration)
* [2] [Choose a License](https://creativecommons.org/choose/?lang=en)

**Comment by acircleda** [comment]
Thanks for the reminder. Please feel free to share and adapt as needed. I have added a CC-BY-NC 4.0 license.
https://github.com/acircleda/RESMHandbook/blob/master/LICENSE
